version: '3.8'

services:
  ubl_to_json_api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - RATELIMIT_DEFAULT=100 per minute
      - RATELIMIT_STORAGE_URL=memory://
    volumes:
      - ./uploads:/app/uploads
